#
# @package Meta Tags phpBB SEO
# @version $Id: services.yml 429 2014-07-09 14:10:55Z  $
# @copyright (c) 2014 www.phpbb-seo.com
# @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
#
# You must indent with 4 spaces instead of 1 tab
#
services: 
    phpbbseo.meta.listener:
        class: phpbbseo\meta\event\listener
        arguments:
            - @config
            - @template
            - @user
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

